//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insurance_backend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("insurance_backend.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string Constanst_Base_Life_Insurance_Additive_Divison_Coef {
            get {
                return ResourceManager.GetString("Constanst_Base_Life_Insurance_Additive_Divison_Coef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyvážená.
        /// </summary>
        public static string Constant_Balanced {
            get {
                return ResourceManager.GetString("Constant_Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konzervativní.
        /// </summary>
        public static string Constant_Consevative {
            get {
                return ResourceManager.GetString("Constant_Consevative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamická.
        /// </summary>
        public static string Constant_Dynamic {
            get {
                return ResourceManager.GetString("Constant_Dynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monthly.
        /// </summary>
        public static string Constant_Monthly {
            get {
                return ResourceManager.GetString("Constant_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string Constant_Months_In_Year {
            get {
                return ResourceManager.GetString("Constant_Months_In_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productId.
        /// </summary>
        public static string Constant_Product_Id {
            get {
                return ResourceManager.GetString("Constant_Product_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yearly.
        /// </summary>
        public static string Constant_Yearly {
            get {
                return ResourceManager.GetString("Constant_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        public static string Constants_Base_Life_Insurance_Coef {
            get {
                return ResourceManager.GetString("Constants_Base_Life_Insurance_Coef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string Constants_Base_Life_Insurance_Invalidity_Coef {
            get {
                return ResourceManager.GetString("Constants_Base_Life_Insurance_Invalidity_Coef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string Constants_Base_Pension_Coef {
            get {
                return ResourceManager.GetString("Constants_Base_Pension_Coef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquipmentPrice.
        /// </summary>
        public static string Constants_Equipment_Price {
            get {
                return ResourceManager.GetString("Constants_Equipment_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiabilityPrice.
        /// </summary>
        public static string Constants_Liability_Price {
            get {
                return ResourceManager.GetString("Constants_Liability_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyPrice.
        /// </summary>
        public static string Constants_Property_Price {
            get {
                return ResourceManager.GetString("Constants_Property_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flat.
        /// </summary>
        public static string Constants_Property_Type_Flat {
            get {
                return ResourceManager.GetString("Constants_Property_Type_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to garage.
        /// </summary>
        public static string Constants_Property_Type_Garage {
            get {
                return ResourceManager.GetString("Constants_Property_Type_Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to house.
        /// </summary>
        public static string Constants_Property_Type_House {
            get {
                return ResourceManager.GetString("Constants_Property_Type_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65.
        /// </summary>
        public static string Constants_Retirement_Age {
            get {
                return ResourceManager.GetString("Constants_Retirement_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Constants_Total {
            get {
                return ResourceManager.GetString("Constants_Total", resourceCulture);
            }
        }
    }
}
