//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insurance_backend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("insurance_backend.Resources.MailTemplates", typeof(MailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;cs&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt;Document&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body style=&quot;font-family: Arial, sans-serif; margin: 0; padding: 0&quot;&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        max-width: 600px;
        ///        margin: auto;
        ///        padding: 20px;
        ///        border: 1px solid #ddd;
        ///        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        ///      &quot;
        ///    &gt;
        ///      &lt;h1 style=&quot;color: #333; text-align: center&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Mail_Life_Insurance_Calculation_Body {
            get {
                return ResourceManager.GetString("Mail_Life_Insurance_Calculation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Life insurance calculation.
        /// </summary>
        public static string Mail_Life_Insurance_Calculation_Subject {
            get {
                return ResourceManager.GetString("Mail_Life_Insurance_Calculation_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;cs&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt;Document&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body style=&quot;font-family: Arial, sans-serif; margin: 0; padding: 0&quot;&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        max-width: 600px;
        ///        margin: auto;
        ///        padding: 20px;
        ///        border: 1px solid #ddd;
        ///        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        ///        background-color: #f9f9f9;
        ///        color: #333;
        ///      &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Mail_Order_Created_Body {
            get {
                return ResourceManager.GetString("Mail_Order_Created_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} succesfully created.
        /// </summary>
        public static string Mail_Order_Created_Subject {
            get {
                return ResourceManager.GetString("Mail_Order_Created_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;cs&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt;Document&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body style=&quot;font-family: Arial, sans-serif; margin: 0; padding: 0&quot;&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        max-width: 600px;
        ///        margin: auto;
        ///        padding: 20px;
        ///        border: 1px solid #ddd;
        ///        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        ///        background-color: #f9f9f9;
        ///        color: #333;
        ///      &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Mail_Order_Deleted_Body {
            get {
                return ResourceManager.GetString("Mail_Order_Deleted_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order succesfully deleted.
        /// </summary>
        public static string Mail_Order_Deleted_Subject {
            get {
                return ResourceManager.GetString("Mail_Order_Deleted_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;cs&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt;Document&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body style=&quot;font-family: Arial, sans-serif; margin: 0; padding: 0&quot;&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        max-width: 600px;
        ///        margin: auto;
        ///        padding: 20px;
        ///        border: 1px solid #ddd;
        ///        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        ///        font-family: Arial, sans-serif;
        ///      &quot;
        ///    &gt;
        ///      &lt;h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Mail_Pension_Scheme_Calculation_Body {
            get {
                return ResourceManager.GetString("Mail_Pension_Scheme_Calculation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Pension scheme calculation.
        /// </summary>
        public static string Mail_Pension_Scheme_Calculation_Subject {
            get {
                return ResourceManager.GetString("Mail_Pension_Scheme_Calculation_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;cs&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt;Document&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body style=&quot;font-family: Arial, sans-serif; margin: 0; padding: 0&quot;&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        max-width: 600px;
        ///        margin: auto;
        ///        padding: 20px;
        ///        border: 1px solid #ddd;
        ///        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        ///        font-family: Arial, sans-serif;
        ///      &quot;
        ///    &gt;
        ///      &lt;h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Mail_Property_Insurance_Calculation_Body {
            get {
                return ResourceManager.GetString("Mail_Property_Insurance_Calculation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Property insurance calculation.
        /// </summary>
        public static string Mail_Property_Insurance_Calculation_Subject {
            get {
                return ResourceManager.GetString("Mail_Property_Insurance_Calculation_Subject", resourceCulture);
            }
        }
    }
}
